### PR TITLE
Rework HTTP Handling

### PR DESCRIPTION
**Pull request by hpr1999**
This PR reworks quite a bit of the http handling with the goals of:

- allowing for different responses based on the accept-header of the request in preparation of #3 
- separating the internal logic of handling a request from serializing it to json and writing the status code / headers

### CODE REVIEW

**Comment by hpr1999** [comment]
In addition to what you've already reviewed, I've added status codes to RequestHandlers and ResponseMappers.
I've also cleaned things up a bit, renaming files, moving some parts into their own files etc.
@derconno

**Review by derconno — CHANGES_REQUESTED** [review]
Well, I am not sure if this is the cleanest way of doing OOP in go, or even if it would be a good idea to mix them into this project, I won't oppose these changes, as this is a toy & learning experience anyways :)

However, I believe that we have arrived at a point where it would make sense do add some documentation on how our code is structured, as well as the core concepts behind it.

Also, `docker build .` fails right now due to missing packages, please fix this before merging. I believe you simply forgot to include your new packages in the Dockerfile.

**Comment by hpr1999** [comment]
> Also, `docker build .` fails right now due to missing packages, please fix this before merging. I believe you simply forgot to include your new packages in the Dockerfile.

yeah that I did... whoops

**Comment by hpr1999** [comment]
I added the new files to the docker file.
Maybe I should also add trying to `docker build .` to the branch pipeline?
Also do you know of a better way than to copy each directory by one or is that just how it's usually done?

**Comment by derconno** [comment]
An option would be to just use `COPY . .` to copy everything, since we use stages, it shouldn't really affect the final image. If we want to keep some files out of the build stage, we could utilize a `.dockerignore` file to keep them out of the build context in the first place. 

Doing a `docker build .` and then discarding the result seems a bit wasteful to me, so I would avoid this if possible.

**Comment by hpr1999** [comment]
> Doing a `docker build .` and then discarding the result

I guess we could also publish it with another tag / as a snapshot, but yeah, it doesn't seem incredibly useful right now.
Still would be nice to catch exactly this kind of error, but it also wouldn't be the end of the world to fix on `master`.

**Comment by hpr1999** [comment]
> could utilize a `.dockerignore` file

that looks good to me, I'll have a look.

**Comment by hpr1999** [comment]
So I've changed it to a `.dockerignore` file, but in retrospect I wonder if there was actually much reason to it at all, since the files only exist at build time anyway, considering the container is build `FROM SCRATCH` in the end.

**Review by derconno — APPROVED** [review]

**Pull request merged**
